spring.application.name=chatsever-backend
spring.datasource.hikari.maximum-pool-size=5
server.port=${PORT:8080}
# JDBC URL - Tui đã thêm chữ .i. vào đúng vị trí cho bạn rồi nè
spring.datasource.url=jdbc:mysql://mysql-2fb1581-minhmap3367-145b.i.aivencloud.com:22695/defaultdb?useSSL=true&requireSSL=true&verifyServerCertificate=false
spring.datasource.username=avnadmin

# MẬT KHẨU: Nhớ bấm vào hình con mắt trên web Aiven để lấy mật khẩu chuẩn nha
spring.datasource.password=AVNS_HsvEk0Dj_fjHZHdKP_y

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Để update để nó tự tạo bảng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
spring.websockets.stomp.message-size-limit=1048576
spring.websockets.stomp.send-buffer-size-limit=1048576